// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	"github.com/libtnb/fiber-skeleton/internal/user/biz"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepo creates a new instance of UserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepo {
	mock := &UserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepo is an autogenerated mock type for the UserRepo type
type UserRepo struct {
	mock.Mock
}

type UserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepo) EXPECT() *UserRepo_Expecter {
	return &UserRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserRepo
func (_mock *UserRepo) Create(ctx context.Context, user *biz.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *biz.User
func (_e *UserRepo_Expecter) Create(ctx any, user any) *UserRepo_Create_Call {
	return &UserRepo_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *UserRepo_Create_Call) Run(run func(ctx context.Context, user *biz.User)) *UserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *biz.User
		if args[1] != nil {
			arg1 = args[1].(*biz.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_Create_Call) Return(err error) *UserRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_Create_Call) RunAndReturn(run func(ctx context.Context, user *biz.User) error) *UserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type UserRepo
func (_mock *UserRepo) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *UserRepo_Expecter) Delete(ctx any, id any) *UserRepo_Delete_Call {
	return &UserRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *UserRepo_Delete_Call) Run(run func(ctx context.Context, id uint)) *UserRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_Delete_Call) Return(err error) *UserRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *UserRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsName provides a mock function for the type UserRepo
func (_mock *UserRepo) ExistsName(ctx context.Context, name string) (bool, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for ExistsName")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_ExistsName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsName'
type UserRepo_ExistsName_Call struct {
	*mock.Call
}

// ExistsName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *UserRepo_Expecter) ExistsName(ctx any, name any) *UserRepo_ExistsName_Call {
	return &UserRepo_ExistsName_Call{Call: _e.mock.On("ExistsName", ctx, name)}
}

func (_c *UserRepo_ExistsName_Call) Run(run func(ctx context.Context, name string)) *UserRepo_ExistsName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_ExistsName_Call) Return(b bool, err error) *UserRepo_ExistsName_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *UserRepo_ExistsName_Call) RunAndReturn(run func(ctx context.Context, name string) (bool, error)) *UserRepo_ExistsName_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type UserRepo
func (_mock *UserRepo) Get(ctx context.Context, id uint) (*biz.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *biz.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*biz.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *biz.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UserRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *UserRepo_Expecter) Get(ctx any, id any) *UserRepo_Get_Call {
	return &UserRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *UserRepo_Get_Call) Run(run func(ctx context.Context, id uint)) *UserRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_Get_Call) Return(user *biz.User, err error) *UserRepo_Get_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id uint) (*biz.User, error)) *UserRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type UserRepo
func (_mock *UserRepo) List(ctx context.Context, page uint, limit uint) ([]*biz.User, int64, error) {
	ret := _mock.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*biz.User
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) ([]*biz.User, int64, error)); ok {
		return returnFunc(ctx, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) []*biz.User); ok {
		r0 = returnFunc(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) int64); ok {
		r1 = returnFunc(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, uint) error); ok {
		r2 = returnFunc(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// UserRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UserRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page uint
//   - limit uint
func (_e *UserRepo_Expecter) List(ctx any, page any, limit any) *UserRepo_List_Call {
	return &UserRepo_List_Call{Call: _e.mock.On("List", ctx, page, limit)}
}

func (_c *UserRepo_List_Call) Run(run func(ctx context.Context, page uint, limit uint)) *UserRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserRepo_List_Call) Return(users []*biz.User, n int64, err error) *UserRepo_List_Call {
	_c.Call.Return(users, n, err)
	return _c
}

func (_c *UserRepo_List_Call) RunAndReturn(run func(ctx context.Context, page uint, limit uint) ([]*biz.User, int64, error)) *UserRepo_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type UserRepo
func (_mock *UserRepo) Update(ctx context.Context, user *biz.User) (*biz.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *biz.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.User) (*biz.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.User) *biz.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *biz.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - user *biz.User
func (_e *UserRepo_Expecter) Update(ctx any, user any) *UserRepo_Update_Call {
	return &UserRepo_Update_Call{Call: _e.mock.On("Update", ctx, user)}
}

func (_c *UserRepo_Update_Call) Run(run func(ctx context.Context, user *biz.User)) *UserRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *biz.User
		if args[1] != nil {
			arg1 = args[1].(*biz.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepo_Update_Call) Return(user1 *biz.User, err error) *UserRepo_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *UserRepo_Update_Call) RunAndReturn(run func(ctx context.Context, user *biz.User) (*biz.User, error)) *UserRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}
