// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/libtnb/fiber-skeleton/internal/order/biz"
)

// Ensure that OrderRepoMock does implement biz.OrderRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.OrderRepo = &OrderRepoMock{}

// OrderRepoMock is a mock implementation of biz.OrderRepo.
//
//	func TestSomethingThatUsesOrderRepo(t *testing.T) {
//
//		// make and configure a mocked biz.OrderRepo
//		mockedOrderRepo := &OrderRepoMock{
//			CreateFunc: func(ctx context.Context, order *biz.Order) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id uint) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id uint) (*biz.Order, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, page int, limit int) ([]*biz.Order, int64, error) {
//				panic("mock out the List method")
//			},
//		}
//
//		// use mockedOrderRepo in code that requires biz.OrderRepo
//		// and then make assertions.
//
//	}
type OrderRepoMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, order *biz.Order) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uint) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id uint) (*biz.Order, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, page int, limit int) ([]*biz.Order, int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Order is the order argument value.
			Order *biz.Order
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Page is the page argument value.
			Page int
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockCreate sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockList   sync.RWMutex
}

// Create calls CreateFunc.
func (mock *OrderRepoMock) Create(ctx context.Context, order *biz.Order) error {
	if mock.CreateFunc == nil {
		panic("OrderRepoMock.CreateFunc: method is nil but OrderRepo.Create was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Order *biz.Order
	}{
		Ctx:   ctx,
		Order: order,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, order)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedOrderRepo.CreateCalls())
func (mock *OrderRepoMock) CreateCalls() []struct {
	Ctx   context.Context
	Order *biz.Order
} {
	var calls []struct {
		Ctx   context.Context
		Order *biz.Order
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *OrderRepoMock) Delete(ctx context.Context, id uint) error {
	if mock.DeleteFunc == nil {
		panic("OrderRepoMock.DeleteFunc: method is nil but OrderRepo.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uint
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedOrderRepo.DeleteCalls())
func (mock *OrderRepoMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  uint
} {
	var calls []struct {
		Ctx context.Context
		ID  uint
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *OrderRepoMock) Get(ctx context.Context, id uint) (*biz.Order, error) {
	if mock.GetFunc == nil {
		panic("OrderRepoMock.GetFunc: method is nil but OrderRepo.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uint
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedOrderRepo.GetCalls())
func (mock *OrderRepoMock) GetCalls() []struct {
	Ctx context.Context
	ID  uint
} {
	var calls []struct {
		Ctx context.Context
		ID  uint
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *OrderRepoMock) List(ctx context.Context, page int, limit int) ([]*biz.Order, int64, error) {
	if mock.ListFunc == nil {
		panic("OrderRepoMock.ListFunc: method is nil but OrderRepo.List was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Page  int
		Limit int
	}{
		Ctx:   ctx,
		Page:  page,
		Limit: limit,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, page, limit)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedOrderRepo.ListCalls())
func (mock *OrderRepoMock) ListCalls() []struct {
	Ctx   context.Context
	Page  int
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Page  int
		Limit int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}
