// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUsers creates a new instance of Users. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsers(t interface {
	mock.TestingT
	Cleanup(func())
}) *Users {
	mock := &Users{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Users is an autogenerated mock type for the Users type
type Users struct {
	mock.Mock
}

type Users_Expecter struct {
	mock *mock.Mock
}

func (_m *Users) EXPECT() *Users_Expecter {
	return &Users_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function for the type Users
func (_mock *Users) Exists(ctx context.Context, id uint) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Users_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type Users_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *Users_Expecter) Exists(ctx any, id any) *Users_Exists_Call {
	return &Users_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *Users_Exists_Call) Run(run func(ctx context.Context, id uint)) *Users_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Users_Exists_Call) Return(b bool, err error) *Users_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *Users_Exists_Call) RunAndReturn(run func(ctx context.Context, id uint) (bool, error)) *Users_Exists_Call {
	_c.Call.Return(run)
	return _c
}
