// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/libtnb/fiber-skeleton/internal/order/biz"
)

// Ensure that Users does implement biz.Users.
// If this is not the case, regenerate this file with mockery.
var _ biz.Users = &Users{}

// Users is a mock implementation of biz.Users.
//
//	func TestSomethingThatUsesUsers(t *testing.T) {
//
//		// make and configure a mocked biz.Users
//		mockedUsers := &Users{
//			ExistsFunc: func(ctx context.Context, id uint) (bool, error) {
//				panic("mock out the Exists method")
//			},
//		}
//
//		// use mockedUsers in code that requires biz.Users
//		// and then make assertions.
//
//	}
type Users struct {
	// ExistsFunc mocks the Exists method.
	ExistsFunc func(ctx context.Context, id uint) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Exists holds details about calls to the Exists method.
		Exists []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
		}
	}
	lockExists sync.RWMutex
}

// Exists calls ExistsFunc.
func (mock *Users) Exists(ctx context.Context, id uint) (bool, error) {
	if mock.ExistsFunc == nil {
		panic("Users.ExistsFunc: method is nil but Users.Exists was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uint
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockExists.Lock()
	mock.calls.Exists = append(mock.calls.Exists, callInfo)
	mock.lockExists.Unlock()
	return mock.ExistsFunc(ctx, id)
}

// ExistsCalls gets all the calls that were made to Exists.
// Check the length with:
//
//	len(mockedUsers.ExistsCalls())
func (mock *Users) ExistsCalls() []struct {
	Ctx context.Context
	ID  uint
} {
	var calls []struct {
		Ctx context.Context
		ID  uint
	}
	mock.lockExists.RLock()
	calls = mock.calls.Exists
	mock.lockExists.RUnlock()
	return calls
}
