// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package biz

import (
	"context"
	"sync"

	"github.com/libtnb/fiber-skeleton/internal/user/biz"
)

// Ensure that UserRepo does implement biz.UserRepo.
// If this is not the case, regenerate this file with mockery.
var _ biz.UserRepo = &UserRepo{}

// UserRepo is a mock implementation of biz.UserRepo.
//
//	func TestSomethingThatUsesUserRepo(t *testing.T) {
//
//		// make and configure a mocked biz.UserRepo
//		mockedUserRepo := &UserRepo{
//			CreateFunc: func(ctx context.Context, user *biz.User) error {
//				panic("mock out the Create method")
//			},
//			DeleteFunc: func(ctx context.Context, id uint) error {
//				panic("mock out the Delete method")
//			},
//			ExistsNameFunc: func(ctx context.Context, name string) (bool, error) {
//				panic("mock out the ExistsName method")
//			},
//			GetFunc: func(ctx context.Context, id uint) (*biz.User, error) {
//				panic("mock out the Get method")
//			},
//			ListFunc: func(ctx context.Context, page int, limit int) ([]*biz.User, int64, error) {
//				panic("mock out the List method")
//			},
//			UpdateFunc: func(ctx context.Context, user *biz.User) (*biz.User, error) {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedUserRepo in code that requires biz.UserRepo
//		// and then make assertions.
//
//	}
type UserRepo struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, user *biz.User) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id uint) error

	// ExistsNameFunc mocks the ExistsName method.
	ExistsNameFunc func(ctx context.Context, name string) (bool, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id uint) (*biz.User, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context, page int, limit int) ([]*biz.User, int64, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, user *biz.User) (*biz.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *biz.User
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
		}
		// ExistsName holds details about calls to the ExistsName method.
		ExistsName []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Page is the page argument value.
			Page int
			// Limit is the limit argument value.
			Limit int
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// User is the user argument value.
			User *biz.User
		}
	}
	lockCreate     sync.RWMutex
	lockDelete     sync.RWMutex
	lockExistsName sync.RWMutex
	lockGet        sync.RWMutex
	lockList       sync.RWMutex
	lockUpdate     sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserRepo) Create(ctx context.Context, user *biz.User) error {
	if mock.CreateFunc == nil {
		panic("UserRepo.CreateFunc: method is nil but UserRepo.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *biz.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, user)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserRepo.CreateCalls())
func (mock *UserRepo) CreateCalls() []struct {
	Ctx  context.Context
	User *biz.User
} {
	var calls []struct {
		Ctx  context.Context
		User *biz.User
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *UserRepo) Delete(ctx context.Context, id uint) error {
	if mock.DeleteFunc == nil {
		panic("UserRepo.DeleteFunc: method is nil but UserRepo.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uint
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedUserRepo.DeleteCalls())
func (mock *UserRepo) DeleteCalls() []struct {
	Ctx context.Context
	ID  uint
} {
	var calls []struct {
		Ctx context.Context
		ID  uint
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// ExistsName calls ExistsNameFunc.
func (mock *UserRepo) ExistsName(ctx context.Context, name string) (bool, error) {
	if mock.ExistsNameFunc == nil {
		panic("UserRepo.ExistsNameFunc: method is nil but UserRepo.ExistsName was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockExistsName.Lock()
	mock.calls.ExistsName = append(mock.calls.ExistsName, callInfo)
	mock.lockExistsName.Unlock()
	return mock.ExistsNameFunc(ctx, name)
}

// ExistsNameCalls gets all the calls that were made to ExistsName.
// Check the length with:
//
//	len(mockedUserRepo.ExistsNameCalls())
func (mock *UserRepo) ExistsNameCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockExistsName.RLock()
	calls = mock.calls.ExistsName
	mock.lockExistsName.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *UserRepo) Get(ctx context.Context, id uint) (*biz.User, error) {
	if mock.GetFunc == nil {
		panic("UserRepo.GetFunc: method is nil but UserRepo.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uint
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedUserRepo.GetCalls())
func (mock *UserRepo) GetCalls() []struct {
	Ctx context.Context
	ID  uint
} {
	var calls []struct {
		Ctx context.Context
		ID  uint
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *UserRepo) List(ctx context.Context, page int, limit int) ([]*biz.User, int64, error) {
	if mock.ListFunc == nil {
		panic("UserRepo.ListFunc: method is nil but UserRepo.List was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Page  int
		Limit int
	}{
		Ctx:   ctx,
		Page:  page,
		Limit: limit,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx, page, limit)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedUserRepo.ListCalls())
func (mock *UserRepo) ListCalls() []struct {
	Ctx   context.Context
	Page  int
	Limit int
} {
	var calls []struct {
		Ctx   context.Context
		Page  int
		Limit int
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *UserRepo) Update(ctx context.Context, user *biz.User) (*biz.User, error) {
	if mock.UpdateFunc == nil {
		panic("UserRepo.UpdateFunc: method is nil but UserRepo.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		User *biz.User
	}{
		Ctx:  ctx,
		User: user,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, user)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedUserRepo.UpdateCalls())
func (mock *UserRepo) UpdateCalls() []struct {
	Ctx  context.Context
	User *biz.User
} {
	var calls []struct {
		Ctx  context.Context
		User *biz.User
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
