template: testify
dir: mocks/{{.SrcPackageName}}
structname: "{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/libtnb/fiber-skeleton/internal:
    config:
      recursive: true
      all: true
      exclude-subpkg-regex:
        - "/pkg(/|$)"
        - "/data$"
        - "/service$"
        - "/server$"
        - "/bootstrap$"
        - "/conf$"
        - "/app$"
