template: testify
dir: mocks/{{.SrcPackageName}}
structname: "{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/libtnb/fiber-skeleton/internal/biz:
    config:
      all: true
      recursive: true
