// Code generated by wire. DO NOT EDIT.
//go:build !wireinject

package app

import (
	"errors"
	"sync"

	biz2 "github.com/libtnb/fiber-skeleton/internal/order/biz"
	data2 "github.com/libtnb/fiber-skeleton/internal/order/data"
	service2 "github.com/libtnb/fiber-skeleton/internal/order/service"
	"github.com/libtnb/fiber-skeleton/internal/platform/bootstrap"
	"github.com/libtnb/fiber-skeleton/internal/platform/conf"
	"github.com/libtnb/fiber-skeleton/internal/platform/server"
	"github.com/libtnb/fiber-skeleton/internal/shared/registry"
	"github.com/libtnb/fiber-skeleton/internal/user/biz"
	"github.com/libtnb/fiber-skeleton/internal/user/data"
	"github.com/libtnb/fiber-skeleton/internal/user/service"
)

func InitializeApp(wireInput0 string) (*App, func() error, error) {
	var wireZero0 *App

	wireRunCleanup := func(cleanup func() error) (cleanupErr error, panicValue any) {
		defer func() { panicValue = recover() }()
		cleanupErr = cleanup()
		return cleanupErr, nil
	}

	var wireCleanups []func() error
	var wireCleanupOnce sync.Once
	var wireCleanupErr error
	var wireCleanupPanic any
	wireCleanup := func() error {
		wireCleanupOnce.Do(func() {
			var cleanupErrors []error
			for index := len(wireCleanups) - 1; index >= 0; index-- {
				cleanupErr, panicValue := wireRunCleanup(wireCleanups[index])
				if cleanupErr != nil {
					cleanupErrors = append(cleanupErrors, cleanupErr)
				}
				if panicValue != nil && wireCleanupPanic == nil {
					wireCleanupPanic = panicValue
				}
			}
			wireCleanupErr = errors.Join(cleanupErrors...)
		})
		if wireCleanupPanic != nil {
			panic(wireCleanupPanic)
		}
		return wireCleanupErr
	}

	wireCommitted := false
	defer func() {
		if !wireCommitted {
			panicValue := recover()
			func() {
				defer func() { _ = recover() }()
				_ = wireCleanup()
			}()
			if panicValue != nil {
				panic(panicValue)
			}
		}
	}()

	wireValue27_0, wireErr27 := conf.Load()
	if wireErr27 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr27, cleanupErr)
	}

	wireValue5_0, wireResourceCleanup5, wireErr5 := bootstrap.NewLogger(wireValue27_0)
	if wireErr5 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr5, cleanupErr)
	}
	if wireResourceCleanup5 != nil {
		wireCleanups = append(wireCleanups, wireResourceCleanup5)
	}

	wireValue9_0, wireErr9 := bootstrap.NewValidator(wireValue27_0)
	if wireErr9 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr9, cleanupErr)
	}

	wireValue28_0 := server.NewVersion(wireInput0)

	wireValue6_0, wireResourceCleanup6, wireErr6 := bootstrap.NewData(wireValue27_0, wireValue5_0)
	if wireErr6 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr6, cleanupErr)
	}
	if wireResourceCleanup6 != nil {
		wireCleanups = append(wireCleanups, wireResourceCleanup6)
	}

	wireValue35_0 := bootstrap.DatabaseHealthCheck(wireValue6_0)

	wireValue39_0 := make(registry.HealthChecks, 0, 1)
	wireValue39_0 = append(wireValue39_0, wireValue35_0)

	wireValue38_0 := server.HealthRoutes(wireValue39_0)

	wireValue40_0 := server.WsRoutes()

	wireValue7_0 := bootstrap.ProvideDB(wireValue6_0)

	wireValue16_0 := data.NewUserRepo(wireValue7_0)

	wireValue17_0 := biz.NewUserUsecase(wireValue16_0)

	wireValue18_0 := service.NewUserService(wireValue17_0, wireValue9_0)

	wireValue41_0 := service.UserRoutes(wireValue18_0)

	wireValue21_0 := data2.NewOrderRepo(wireValue7_0)

	wireValue22_0 := data2.NewUsers(wireValue17_0)

	wireValue10_0 := bootstrap.NewBus(wireValue5_0)

	wireValue23_0 := biz2.NewOrderUsecase(wireValue21_0, wireValue22_0, wireValue10_0)

	wireValue24_0 := service2.NewOrderService(wireValue23_0, wireValue9_0)

	wireValue43_0 := service2.OrderRoutes(wireValue24_0)

	wireValue45_0 := make(registry.Routes, 0, 4)
	wireValue45_0 = append(wireValue45_0, wireValue38_0)
	wireValue45_0 = append(wireValue45_0, wireValue40_0)
	wireValue45_0 = append(wireValue45_0, wireValue41_0)
	wireValue45_0 = append(wireValue45_0, wireValue43_0)

	wireValue30_0, wireErr30 := server.NewRouter(wireValue27_0, wireValue5_0, wireValue9_0, wireValue28_0, wireValue45_0)
	if wireErr30 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr30, cleanupErr)
	}

	wireValue11_0, wireErr11 := bootstrap.NewMigrate(wireValue7_0, wireValue5_0)
	if wireErr11 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr11, cleanupErr)
	}

	wireValue36_0 := bootstrap.Heartbeat(wireValue5_0)

	wireValue46_0 := make(registry.Jobs, 0, 1)
	wireValue46_0 = append(wireValue46_0, wireValue36_0)

	wireValue29_0, wireErr29 := bootstrap.NewCron(wireValue5_0, wireValue46_0)
	if wireErr29 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr29, cleanupErr)
	}

	wireValue44_0 := service2.NewOrderPlacedLogger(wireValue10_0, wireValue5_0)

	wireValue47_0 := make(registry.Subscriptions, 0, 1)
	wireValue47_0 = append(wireValue47_0, wireValue44_0)

	wireValue32_0 := NewApp(wireValue27_0, wireValue30_0, wireValue11_0, wireValue29_0, wireValue47_0)

	wireCommitted = true

	return wireValue32_0, wireCleanup, nil
}

func InitializeCLI() (*Cli, func() error, error) {
	var wireZero0 *Cli

	wireRunCleanup := func(cleanup func() error) (cleanupErr error, panicValue any) {
		defer func() { panicValue = recover() }()
		cleanupErr = cleanup()
		return cleanupErr, nil
	}

	var wireCleanups []func() error
	var wireCleanupOnce sync.Once
	var wireCleanupErr error
	var wireCleanupPanic any
	wireCleanup := func() error {
		wireCleanupOnce.Do(func() {
			var cleanupErrors []error
			for index := len(wireCleanups) - 1; index >= 0; index-- {
				cleanupErr, panicValue := wireRunCleanup(wireCleanups[index])
				if cleanupErr != nil {
					cleanupErrors = append(cleanupErrors, cleanupErr)
				}
				if panicValue != nil && wireCleanupPanic == nil {
					wireCleanupPanic = panicValue
				}
			}
			wireCleanupErr = errors.Join(cleanupErrors...)
		})
		if wireCleanupPanic != nil {
			panic(wireCleanupPanic)
		}
		return wireCleanupErr
	}

	wireCommitted := false
	defer func() {
		if !wireCommitted {
			panicValue := recover()
			func() {
				defer func() { _ = recover() }()
				_ = wireCleanup()
			}()
			if panicValue != nil {
				panic(panicValue)
			}
		}
	}()

	wireValue27_0, wireErr27 := conf.Load()
	if wireErr27 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr27, cleanupErr)
	}

	wireValue5_0, wireResourceCleanup5, wireErr5 := bootstrap.NewLogger(wireValue27_0)
	if wireErr5 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr5, cleanupErr)
	}
	if wireResourceCleanup5 != nil {
		wireCleanups = append(wireCleanups, wireResourceCleanup5)
	}

	wireValue6_0, wireResourceCleanup6, wireErr6 := bootstrap.NewData(wireValue27_0, wireValue5_0)
	if wireErr6 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr6, cleanupErr)
	}
	if wireResourceCleanup6 != nil {
		wireCleanups = append(wireCleanups, wireResourceCleanup6)
	}

	wireValue7_0 := bootstrap.ProvideDB(wireValue6_0)

	wireValue11_0, wireErr11 := bootstrap.NewMigrate(wireValue7_0, wireValue5_0)
	if wireErr11 != nil {
		wireCommitted = true
		cleanupErr := wireCleanup()
		return wireZero0, nil, errors.Join(wireErr11, cleanupErr)
	}

	wireValue36_0 := bootstrap.MigrateCommand(wireValue11_0)

	wireValue16_0 := data.NewUserRepo(wireValue7_0)

	wireValue17_0 := biz.NewUserUsecase(wireValue16_0)

	wireValue41_0 := service.UserCommand(wireValue17_0)

	wireValue44_0 := make(registry.Commands, 0, 2)
	wireValue44_0 = append(wireValue44_0, wireValue36_0)
	wireValue44_0 = append(wireValue44_0, wireValue41_0)

	wireValue31_0 := newRootCommand(wireValue44_0)

	wireValue33_0 := NewCli(wireValue31_0)

	wireCommitted = true

	return wireValue33_0, wireCleanup, nil
}
