// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package biz

import (
	"context"

	"github.com/libtnb/fiber-skeleton/internal/order/biz"
	mock "github.com/stretchr/testify/mock"
)

// NewOrderRepo creates a new instance of OrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepo {
	mock := &OrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OrderRepo is an autogenerated mock type for the OrderRepo type
type OrderRepo struct {
	mock.Mock
}

type OrderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepo) EXPECT() *OrderRepo_Expecter {
	return &OrderRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OrderRepo
func (_mock *OrderRepo) Create(ctx context.Context, order *biz.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *biz.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OrderRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - order *biz.Order
func (_e *OrderRepo_Expecter) Create(ctx any, order any) *OrderRepo_Create_Call {
	return &OrderRepo_Create_Call{Call: _e.mock.On("Create", ctx, order)}
}

func (_c *OrderRepo_Create_Call) Run(run func(ctx context.Context, order *biz.Order)) *OrderRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *biz.Order
		if args[1] != nil {
			arg1 = args[1].(*biz.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepo_Create_Call) Return(err error) *OrderRepo_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepo_Create_Call) RunAndReturn(run func(ctx context.Context, order *biz.Order) error) *OrderRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type OrderRepo
func (_mock *OrderRepo) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OrderRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type OrderRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *OrderRepo_Expecter) Delete(ctx any, id any) *OrderRepo_Delete_Call {
	return &OrderRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *OrderRepo_Delete_Call) Run(run func(ctx context.Context, id uint)) *OrderRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepo_Delete_Call) Return(err error) *OrderRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OrderRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *OrderRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type OrderRepo
func (_mock *OrderRepo) Get(ctx context.Context, id uint) (*biz.Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *biz.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*biz.Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *biz.Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*biz.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OrderRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *OrderRepo_Expecter) Get(ctx any, id any) *OrderRepo_Get_Call {
	return &OrderRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *OrderRepo_Get_Call) Run(run func(ctx context.Context, id uint)) *OrderRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OrderRepo_Get_Call) Return(order *biz.Order, err error) *OrderRepo_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *OrderRepo_Get_Call) RunAndReturn(run func(ctx context.Context, id uint) (*biz.Order, error)) *OrderRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type OrderRepo
func (_mock *OrderRepo) List(ctx context.Context, page int, limit int) ([]*biz.Order, int64, error) {
	ret := _mock.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*biz.Order
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]*biz.Order, int64, error)); ok {
		return returnFunc(ctx, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []*biz.Order); ok {
		r0 = returnFunc(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = returnFunc(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// OrderRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type OrderRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *OrderRepo_Expecter) List(ctx any, page any, limit any) *OrderRepo_List_Call {
	return &OrderRepo_List_Call{Call: _e.mock.On("List", ctx, page, limit)}
}

func (_c *OrderRepo_List_Call) Run(run func(ctx context.Context, page int, limit int)) *OrderRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OrderRepo_List_Call) Return(orders []*biz.Order, n int64, err error) *OrderRepo_List_Call {
	_c.Call.Return(orders, n, err)
	return _c
}

func (_c *OrderRepo_List_Call) RunAndReturn(run func(ctx context.Context, page int, limit int) ([]*biz.Order, int64, error)) *OrderRepo_List_Call {
	_c.Call.Return(run)
	return _c
}
