name: Mockery
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  mockery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          cache: true
          go-version-file: go.mod
      - name: Generate Mocks
        run: go tool mockery
      - name: Verify mocks are up to date
        run: |
          git add -N mocks
          git diff --exit-code mocks/
